services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - caddy_data:/data
      - caddy_config:/config
    labels:
      caddy_controlled_server: ""
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  caddy:
    external: true

volumes:
  caddy_data:
  caddy_config:
