services:
  nats:
    image: nats:2.10-alpine
    container_name: genesis-nats
    hostname: nats
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    
    command:
      - "--name=genesis-nats"
      - "--config=/etc/nats/nats.conf"  # 使用配置文件
    
    volumes:
      - nats-data:/data
      - ./nats.conf:/etc/nats/nats.conf:ro  # 挂载配置文件
    
    networks:
      - genesis-net
      - caddy
    
    deploy:
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 192M
    
    labels:
      caddy: nats.ceyewan.xyz
      caddy.reverse_proxy: "{{upstreams 8222}}"
    
    ports:
      - "127.0.0.1:4222:4222"

networks:
  genesis-net:
    external: true
  caddy:
    external: true

volumes:
  nats-data: