version: '3.8'

services:
  new-api:
    image: calciumion/new-api:latest
    container_name: new-api
    restart: unless-stopped
    environment:
      # MySQL 连接（使用环境变量）
      - SQL_DSN=root:${MYSQL_PASSWORD}@tcp(mysql:3306)/newapi
      # Redis 连接（如有密码请补充）
      - REDIS_CONN_STRING=redis://:${REDIS_PASSWORD}@redis:6379
      # 基本配置
      - PORT=3000
      - TZ=Asia/Shanghai
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    networks:
      - genesis-net
      - caddy
    labels:
      # Caddy 反向代理配置（请替换域名和邮箱）
      caddy: newapi.yourdomain.com
      caddy.reverse_proxy: "{{upstreams 3000}}"

networks:
  genesis-net:
    external: true
  caddy:
    external: true
