services:
  redis:
    image: redis:7.2-alpine
    container_name: genesis-redis
    hostname: redis
    restart: unless-stopped
    
    command:
      - redis-server
      - --requirepass
      - ${REDIS_PASSWORD} # 从 .env 文件读取
      - --maxmemory
      - 320mb
      - --maxmemory-policy
      - allkeys-lru
      - --appendonly
      - yes
    
    volumes:
      - redis-data:/data
    
    # 使用外部网络
    networks:
      - genesis-net
    
    deploy:
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 192M
    
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"

    ports:
      - "127.0.0.1:6379:6379" # 只允许服务器本机访问

networks:
  genesis-net:
    external: true

volumes:
  redis-data: